
from setuptools import setup, find_packages

setup(
    name='ey_provider_agent',
    version='1.0.0',
    packages=find_packages(include=['agents', 'pipeline', 'utils', 'tools']),
    install_requires=[
        "pandas",
        "numpy",
        "python-dateutil",
        "streamlit",
        "streamlit-option-menu",
        "altair",
        "pydeck",
        "matplotlib",
        "plotly",
        "langchain",
        "langchain-core",
        "langchain-community",
        "langchain-openai",
        "langsmith",
        "tiktoken",
        "pymupdf",
        "pypdf",
        "pdfminer.six",
        "requests",
        "urllib3",
        "reportlab>=4.0.0",
        "beautifulsoup4==4.12.3",
        "six==1.16.0",
        "sqlalchemy",
        "python-dotenv",
        "tabulate",
    ],
)
